// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uadphirkhxqldnedtqnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZHBoaXJraHhxbGRuZWR0cW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjk5MjgsImV4cCI6MjA2MDkwNTkyOH0.TtA4kfOW_POQtBNZBmqj4lx9m1TSzgAAo0Fwcdhf040";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);